
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { usePrintJobs } from '@/hooks/usePrintJobs';

interface PrintJobCreationDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

const PrintJobCreationDialog: React.FC<PrintJobCreationDialogProps> = ({
  isOpen,
  onClose
}) => {
  const { createPrintJob } = usePrintJobs();
  const [loading, setLoading] = useState(false);
  
  const [jobData, setJobData] = useState({
    productName: '',
    productId: '',
    eanNumber: '',
    quantity: 1,
    material: 'PLA',
    color: '',
    priority: 5,
    notes: ''
  });

  const materials = ['PLA', 'PETG', 'ABS', 'TPU', 'Wood Fill', 'Carbon Fiber'];

  const handleSubmit = async () => {
    if (!jobData.productName) return;
    
    setLoading(true);
    try {
      await createPrintJob({
        product_id: jobData.productId || undefined,
        product_name: jobData.productName,
        ean_number: jobData.eanNumber || undefined,
        quantity: jobData.quantity,
        material: jobData.material,
        color: jobData.color || undefined,
        priority: jobData.priority,
        notes: jobData.notes || undefined,
        source_type: 'manual'
        // job_number will be auto-generated by the database trigger
      });

      onClose();
      resetForm();
    } catch (error) {
      console.error('Error creating print job:', error);
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setJobData({
      productName: '',
      productId: '',
      eanNumber: '',
      quantity: 1,
      material: 'PLA',
      color: '',
      priority: 5,
      notes: ''
    });
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Print Job erstellen</DialogTitle>
          <DialogDescription>
            Erstellen Sie einen neuen Druckauftrag
          </DialogDescription>
        </DialogHeader>
        
        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="productName">Produktname *</Label>
            <Input
              id="productName"
              value={jobData.productName}
              onChange={(e) => setJobData(prev => ({ ...prev, productName: e.target.value }))}
              placeholder="Name des Produkts..."
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="productId">Produkt-ID (Optional)</Label>
            <Input
              id="productId"
              value={jobData.productId}
              onChange={(e) => setJobData(prev => ({ ...prev, productId: e.target.value }))}
              placeholder="Eindeutige Produkt-ID..."
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="eanNumber">EAN-Nummer (Optional)</Label>
            <Input
              id="eanNumber"
              value={jobData.eanNumber}
              onChange={(e) => setJobData(prev => ({ ...prev, eanNumber: e.target.value }))}
              placeholder="EAN-Code..."
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="quantity">Stückzahl</Label>
            <Input
              id="quantity"
              type="number"
              min="1"
              value={jobData.quantity}
              onChange={(e) => setJobData(prev => ({ ...prev, quantity: parseInt(e.target.value) || 1 }))}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="material">Material</Label>
            <Select value={jobData.material} onValueChange={(value) => setJobData(prev => ({ ...prev, material: value }))}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {materials.map((material) => (
                  <SelectItem key={material} value={material}>
                    {material}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="color">Farbe (Optional)</Label>
            <Input
              id="color"
              value={jobData.color}
              onChange={(e) => setJobData(prev => ({ ...prev, color: e.target.value }))}
              placeholder="z.B. Rot, Blau, Transparent..."
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="priority">Priorität (1-10)</Label>
            <Input
              id="priority"
              type="number"
              min="1"
              max="10"
              value={jobData.priority}
              onChange={(e) => setJobData(prev => ({ ...prev, priority: parseInt(e.target.value) || 5 }))}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="notes">Notizen (Optional)</Label>
            <Textarea
              id="notes"
              value={jobData.notes}
              onChange={(e) => setJobData(prev => ({ ...prev, notes: e.target.value }))}
              placeholder="Besondere Anweisungen oder Hinweise..."
            />
          </div>

          <Button 
            onClick={handleSubmit} 
            className="w-full"
            disabled={!jobData.productName || loading}
          >
            {loading ? 'Erstelle Job...' : 'Job erstellen'}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default PrintJobCreationDialog;
