// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuxgxkemywnyranlhsjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1eGd4a2VteXdueXJhbmxoc2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzQyMTUsImV4cCI6MjA2MzkxMDIxNX0.ilp_enK4vvX2Vy8EpogSh9XGQN-GaMI0Yb8YyVPtIqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);